### ISSUE TITLE
Credentials

### ISSUE THREAD

**Issue by mwilchek** [tatornator12/Item-Dependencies-Tree#1]
If I want to test this, can I have your username and password? ;)

Also I noticed you created some logging objects - I'll just leave this documentation for incredibly easy to use python logging library:
https://docs.python.org/3/howto/logging.html

**Comment by tatornator12** [comment]
Haha, I definitely need to get better at logging - so little time for it!

This is a pet project of mine due to our technology not having the ability to track what's embedded within web apps. Trying to prototype it at the moment.

**Comment by mwilchek** [comment]
Haha ah ok. Well looks pretty cool so far!
